### ISSUE TITLE
TCC preprocessor error

### ISSUE THREAD

**Issue by TheMode** [ibireme/yyjson#233]
**Describe the bug**
yyjson.h generates this

```
engine/yyjson.h:422: error: bad preprocessor expression: #if ( 0 && 0 ) || ( 1 && ! 0 ) || 0 >= 1800 || 199901L >= 199901L
make: *** [build/circuit_json.o] Error 1
```

Referring to this macro
```c
/** stdbool (C89 compatible) */
#if (defined(YYJSON_HAS_STDBOOL_H) && YYJSON_HAS_STDBOOL_H) || \
    (yyjson_has_include(<stdbool.h>) && !defined(__STRICT_ANSI__)) || \
    YYJSON_MSC_VER >= 1800 || YYJSON_STDC_VER >= 199901L
```

And not directly related, those pragma warning also appear (after removing the problematic macro)
```
In file included from engine/yyjson.c:23:
engine/yyjson.h:480: warning: #pragma GCC ignored
In file included from engine/yyjson.c:23:
engine/yyjson.h:481: warning: #pragma GCC ignored
engine/yyjson.c:39: warning: #pragma GCC ignored
engine/yyjson.c:40: warning: #pragma GCC ignored
engine/yyjson.c:41: warning: #pragma GCC ignored
engine/yyjson.c:42: warning: #pragma GCC ignored
engine/yyjson.c:43: warning: #pragma GCC ignored
```

**Your environment**
 - OS: macOS 15.6.1
 - Compiler: tcc version 0.9.28rc 2025-09-08 mob@38ab5f65 (AArch64 Darwin)

**Additional context**

**Comment by ibireme** [comment]
Thanks for the report!

I was able to reproduce this with the latest code from https://github.com/TinyCC/tinycc. 
It looks like tcc does support `__has_include`, but in some cases it throws an error.

Here's a minimal repro:
```c
#ifndef yyjson_has_include
#   ifdef __has_include
#       define yyjson_has_include(x) __has_include(x)
#   else
#       define yyjson_has_include(x) 0
#   endif
#endif

// tcc report error: error: bad preprocessor expression: #if 1 && 1
#if yyjson_has_include(<stdbool.h>) || 1
#   include <stdbool.h>
#endif

// tcc ok
#if __has_include(<stdbool.h>) || 1
#   include <stdbool.h>
#endif

// tcc ok
#if 1 || yyjson_has_include(<stdbool.h>)
#   include <stdbool.h>
#endif
```

For yyjson, the fix is simple — just changing the order of the conditions avoids the issue:
```c
#if (defined(YYJSON_HAS_STDBOOL_H) && YYJSON_HAS_STDBOOL_H) || \
    YYJSON_MSC_VER >= 1800 || YYJSON_STDC_VER >= 199901L || \
    (yyjson_has_include(<stdbool.h>) && !defined(__STRICT_ANSI__))
```
